[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
capstone = "CEsmX47xiPVyeaBcH6mmgkwGNQhU77Xwim7mSTez5cK4"

[programs.localnet]
capstone = "CEsmX47xiPVyeaBcH6mmgkwGNQhU77Xwim7mSTez5cK4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
